### ISSUE TITLE
Zoom Image Issue

### ISSUE THREAD

**Issue by mrosadilla23** [rfe-nixos/FEC#48]
#### Description
When in the zoomed in state, I am not able to hover over the entire image, some of the left side of it is obscured.

#### Files
https://github.com/rfe-nixos/FEC/blob/025c1d4c91e14ecdbe8439ab22a42bbc8cca45a3/client/src/product-details/Modal.jsx#L73

#### Screenshots
![Screen Shot 2022-07-23 at 10 43 58 AM](https://user-images.githubusercontent.com/99907417/180609974-19707965-4c9f-4642-bbb0-f705ea480875.png)
2

#### To reproduce

Click on main image in gallery to make fullscreen and then click to enter zoom state, then try to hover to left side of the image.

#### Tasks

- [ ]  Change mouse move to take in e.native.offsetX/Y
- [ ] Divide offsetX by the events ClientWidth property
- [ ] Divide OffsetY by the even's ClientHeight property
- [ ] give that to transform origin as percentages rather than px values.
