### ISSUE TITLE
Could DRY this piece of code up

### ISSUE THREAD

**Issue by mrosadilla23** [rfe-nixos/FEC#49]
#### Description
THis snippet of code has 3 almost identical sections of code in an if/else chain

#### Files
https://github.com/rfe-nixos/FEC/blob/025c1d4c91e14ecdbe8439ab22a42bbc8cca45a3/client/src/product-details/Modal.jsx#L31-L78

#### To reproduce

Not really a way to reproduce it.

#### Tasks

- [ ] Create a jsx component to display what is inside the if statements
- [ ] have that compoenent take in props based on the conditions set in the original code
- [ ] define the render logic in a way that you get similar results, i.e  `<div>{range[0] === 0 ? &#9002 : &#9001} </div>`
