### ISSUE TITLE
product card link could be optimized

### ISSUE THREAD

**Issue by code402b** [rfe-nixos/FEC#60]
#### Description
- Only the title text of the card is a clickable link, and it doesn't provide cursor feedback when hovered over.
- Linking is implemented by setting a state variable which rerenders the App. This approach has a lot of appeal, but in this case I don't think it creates the ideal behavior, particularly the fact that the browser's back/forward will not work using this method.

#### Screenshots (if ui based)
![spotty link](http://g.recordit.co/Ab3TeljRHh.gif)

#### To Reproduce
Attempt to click on product card links

#### Tasks (optional)
- [ ] set a click handler on the outer card container component that handles linking, so that the entire card is clickable.
- [ ] set a cursor:pointer css property on the card's hover state to give feedback to the user
- [ ] consider using a URL-based method of linking to enable the [browser history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)

https://github.com/rfe-nixos/FEC/blob/025c1d4c91e14ecdbe8439ab22a42bbc8cca45a3/client/src/related-items/product.jsx#L55-L94

**Comment by ianzuber221** [comment]
Thanks Anthony great idea!
